export const principleNames: Record<number, string> = {
  1: 'Every system has a constraint',
  2: 'A chain is only as strong as its weakest link',
  3: 'The five focusing steps',
  4: 'An hour lost at the constraint is lost for the whole factory',
  5: 'Speeding up a station that is not the constraint is a mirage',
  6: "What's best for one station isn't best for the whole factory",
  13: 'Delays pass down the line and add up',
  14: 'Variation piles up at the constraint',
  15: 'A perfectly balanced line ships less than its average',
  16: 'The constraint sets the pace for the whole factory',
  17: 'A buffer protects the constraint from hiccups upstream',
  18: 'Release work only as fast as the constraint uses it',
  19: 'The buffer shows which problems cost output',
  20: "The batch you move doesn't have to be the batch you make",
  21: 'Small batches suit stations with time to spare',
  22: 'Bigger batches at the constraint save changeover time',
  23: 'Smaller batches cut waiting and inventory',
  26: 'Sometimes the constraint is the market, not the factory',
  27: 'A rule can be the constraint',
  28: 'Rank products by what they earn per minute of the constraint',
  29: 'Cost reports can point the wrong way',
  31: 'There is always a next constraint',
  32: "Don't let old rules become the constraint",
  33: 'Balance the flow, not the capacity',
  36: 'Keep enough materials on hand to ride out a late delivery',
  37: "Scrap after the constraint wastes the constraint's time",
  38: 'A change in the product mix can move the constraint',
  39: 'Changing priorities at the constraint costs output',
  40: 'Forecasts are always wrong',
  41: 'Make what customers take, not what the forecast says',
  42: 'Forecast the total, and decide the details as late as you can',
}
