import { choice, forTier, truth } from './make.ts'

// Tier 3, Drum, buffer, rope: the standard way to run a factory around its constraint.
export const tier3 = forTier(3, [
  choice(
    '3-1',
    'tier3-rope',
    'In drum, buffer, rope, what is the drum?',
    'The constraint, which sets the pace for the factory',
    ['The first station in the line, where all work begins', 'The pile of work waiting in front of the constraint', 'The rule that lets new work into the factory'],
    'The drum is the constraint. Like a drum setting the beat for a march, it sets the pace that everyone else in the factory works to.',
  ),
  choice(
    '3-2',
    'tier3-rope',
    'In drum, buffer, rope, what is the buffer?',
    'A small pile of work in front of the constraint, so it never has to wait',
    [
      'A spare machine kept ready in case the constraint breaks down',
      'A cushion of extra cash kept to cover wages in a slow month',
      'A rule that stops the first station whenever the whole line looks full',
    ],
    'The buffer is a small pile of work in front of the constraint. It keeps the constraint working when something upstream hiccups, so that the whole factory does not lose output.',
  ),
  choice(
    '3-3',
    'tier3-rope',
    'In drum, buffer, rope, what does the rope do?',
    'It lets work into the line only as fast as the constraint uses it',
    ['It releases new work whenever the first station is free', 'It moves finished parts to the next station as soon as they are done', 'It limits how many hours a station may run in a day'],
    'The rope ties the start of the line to the pace of the constraint, so work never goes in faster than the constraint can use it. That keeps piles small and orders moving.',
  ),
  choice(
    '3-4',
    'tier3-rope',
    'What is the main effect of tying the rope to the constraint?',
    'Less work sits on the floor and orders wait less, but output stays about the same',
    [
      'The line ships noticeably more parts, because the stations then work faster than before',
      'The line ships somewhat less, because the first station is held back',
      'There is little change, because the constraint still works at the same speed',
    ],
    'The constraint ships the same either way, so output does not change. But work stops flooding in faster than the constraint can use it, so the pile on the floor and the time each order waits both shrink.',
  ),
  choice(
    '3-5',
    'tier3-rope',
    'A rope releases new work into the line at the pace of one station. Which station should set that pace?',
    'The constraint',
    ['The first station', 'The last station', 'The fastest station'],
    "The rope ties the release of new work to the constraint's pace. If the first station set the pace, work would still flood in as fast as that station can take it. If the last station set it, the rope would count work already past the constraint, and the constraint could end up starved.",
  ),
  choice(
    '3-6',
    'tier3-size',
    'A constraint takes 4 minutes per part. The station feeding it sometimes stops for up to 30 minutes. About how many parts should wait in front of the constraint so it keeps working through a stop?',
    'About 8 parts',
    ['About 4 parts', 'About 15 parts', 'About 30 parts'],
    'In 30 minutes the constraint works through 30 ÷ 4 = 7.5 parts, so about 8 parts waiting will last through the stop. Far fewer lets the constraint run dry, and far more only adds inventory.',
  ),
  choice(
    '3-7',
    'tier3-size',
    'How big should the buffer in front of the constraint be?',
    'Big enough to last through the longest usual stop upstream, and no bigger',
    [
      'Big enough to cover the average stop upstream, since longer stops are rare',
      'Big enough to cover an hour of work, whatever the stops upstream are like',
      'Big enough to hold everything the first station makes in a whole shift',
    ],
    'Too small, and the constraint runs dry whenever a stop upstream lasts longer than the buffer does. Too big, and you add inventory, space, and waiting without shipping any more.',
  ),
  choice(
    '3-8',
    'tier3-read',
    'The buffer in front of the constraint runs empty every time a certain machine upstream stops. What does this tell you?',
    "That machine's stops cost the factory output, so fixing them comes first",
    ['That machine is the constraint', 'The buffer is too big and should be removed', "That machine's stops do not really matter, because it is not the constraint itself"],
    'The buffer exists to cover upstream hiccups. When a stop drains it and the constraint goes without work, that problem is costing output. Problems the buffer absorbs cost nothing.',
  ),
  truth(
    '3-9',
    'tier3-read',
    'A problem that piles up parts after the constraint costs the factory more than one that leaves the constraint without work.',
    false,
    'A pile after the constraint does not hurt output, because the constraint keeps working. A problem that leaves the constraint without work, for example by emptying the buffer in front of it, is the one that costs output.',
  ),
  truth(
    '3-10',
    'tier3-size',
    "Once the buffer already covers the longest usual stop upstream, making it bigger raises the factory's output.",
    false,
    'Once the buffer covers the usual stops, the constraint is already protected. More work in the buffer only ties up money, takes space, and makes every order wait longer.',
  ),
  truth(
    '3-11',
    'tier3-rope',
    'In drum, buffer, rope, the buffer sits in front of the constraint, not in front of the first station.',
    true,
    'The buffer is a small pile of work in front of the constraint, so that it never has to wait. The first station is where the rope releases work, but the pile that protects the constraint sits right in front of the constraint itself.',
  ),
  truth(
    '3-12',
    'tier3-size',
    'A small pile of work waiting in front of the constraint is not waste: it keeps the constraint working when something upstream stops.',
    true,
    'That pile is protection. If it is just big enough to cover the usual hiccup, it costs little and saves output that would otherwise be lost for the whole factory.',
  ),
])
